apiVersion: apps/v1
kind: Deployment
metadata:
  name: gohw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gohw
  template:
    metadata:
      labels:
        app: gohw
    spec:
      containers:
      - name: hwapp
        image: tstahlfsu/gohwapp:latest
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: gohw-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: gohw
